name: publish on release conda
on:
  release:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: "Setup Conda"
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge, bioconda
      - name: "Install Conda development packages"
        run: |
          conda install conda-build
          conda install -c anaconda anaconda-client
      - name: "Build and upload package"
        run: |
          mkdir conda-build
          conda build . --no-build-id  --output-folder ./conda-build
          conda convert -p all ./conda-build/**/netzoopy*.bz2 --output-dir ./conda-build
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u netzoo --no-progress ./conda-build/**/netzoopy*.bz2
