name: Build netZooPy with Rattler

on:
  push:
    branches:
      - master
      - devel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rattler and update PATH
        run: |
          curl -fsSL https://prefix.dev/install.sh | bash
          echo "$HOME/.rattler/bin" >> $GITHUB_PATH
          echo "export PATH=$HOME/.rattler/bin:\$PATH" >> $GITHUB_ENV
          export PATH="$HOME/.rattler/bin:$PATH"
          which rattler-build
          rattler-build --version

      - name: Build with Rattler
        run: |
          mkdir -p rattler-build
          rattler-build build --recipe recipe/ --output rattler-build/

      - name: Show built package
        run: |
          ls -lh rattler-build/**/*.tar.bz2
