name: new test conda build
on:
  push:
    branches:
      - master
      - devel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Conda"
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: false
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge, bioconda
      - name: "Install Conda development packages"
        run: |
          conda install conda-build
          conda install conda-verify
          conda install -c anaconda anaconda-client
      - name: "Verify Conda Build Installation"
        run: |
          conda list | grep conda-build
      - name: "Build and upload package"
        run: |
          mkdir conda-build
          conda build . --no-build-id  --output-folder ./conda-build -c conda-forge
          ls conda-build/**/netzoopy*
          conda install "urllib3<2"
