name: test-conda-build-all-artifacts
on:
  push:
    branches: [devel]
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniforge (Conda)
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge  # Use Mambaforge if you're confident it's available
          use-mamba: true
          auto-update-conda: true

      - name: Set CONDA_PACKAGE_FORMAT=2 (for .conda files)
        run: echo "CONDA_PACKAGE_FORMAT=2" >> $GITHUB_ENV

      - name: Install conda-build
        run: mamba install -y conda-build

      - name: Build Conda Package
        run: |
          mkdir -p conda-build
          conda build conda/ --output-folder conda-build --no-build-id -c conda-forge
