name: Build netZooPy with Rattler

on:
  push:
    branches:
      - master
      - devel
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build conda package
      uses: prefix-dev/rattler-build-action@v0.2.33

      - name: Show built package
        run: |
          ls -lh rattler-build/**/*.tar.bz2
