name: Build netZooPy with Rattler

on:
  push:
    branches:
      - master
      - devel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rattler from Prefix.dev release
        run: |
          curl -L https://github.com/prefix-dev/rattler-build/releases/download/v0.43.0/rattler-build-x86_64-unknown-linux-musl.tar.gz -o rattler-build.tar.gz
          mkdir -p $HOME/.rattler/bin
          tar -xzf rattler-build.tar.gz -C $HOME/.rattler/bin --strip-components=1
          echo "$HOME/.rattler/bin" >> $GITHUB_PATH
          echo "export PATH=$HOME/.rattler/bin:\$PATH" >> $GITHUB_ENV
          export PATH="$HOME/.rattler/bin:$PATH"
          rattler-build --version

      - name: Build with Rattler
        run: |
          mkdir -p rattler-build
          rattler-build build --recipe recipe/ --output rattler-build/

      - name: Show built package
        run: |
          ls -lh rattler-build/**/*.tar.bz2
